// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA9Z-DY0PItWMQWo990KSuwURHE7DYUrc',
    appId: '1:445779417374:web:1eb04c44be04762972910f',
    messagingSenderId: '445779417374',
    projectId: 'tasks-d05cc',
    authDomain: 'tasks-d05cc.firebaseapp.com',
    storageBucket: 'tasks-d05cc.appspot.com',
    measurementId: 'G-KP1HTGFTVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmWyzwrvx8RerWh2ckrph6YfIh075Xqt0',
    appId: '1:445779417374:android:e4c632c05372a53b72910f',
    messagingSenderId: '445779417374',
    projectId: 'tasks-d05cc',
    storageBucket: 'tasks-d05cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlX5fDTdUQ7Knl8M36DKKkB1UNjbGrRkk',
    appId: '1:445779417374:ios:75ca15ab545c736a72910f',
    messagingSenderId: '445779417374',
    projectId: 'tasks-d05cc',
    storageBucket: 'tasks-d05cc.appspot.com',
    iosBundleId: 'aryan.com.tasks',
  );
}
